pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_guider_path: "./pretrained_weights/pose_guider.pth"
motion_module_path: "./pretrained_weights/motion_module.pth"
pretrained_wav2vec_path: "./pretrained_weights/"

# denoising_unet_path: "./exp_output/stage1/denoising_unet-3000.pth"
# reference_unet_path: "./exp_output/stage1/reference_unet-3000.pth"
# audio_guider_path: "./exp_output/stage1/audio_guider-3000.pth"
# motion_module_path: "./exp_output/stage2/motion-3000"
inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/ref_images/anyone-2.png":
    # - "./configs/inference/audio_files/example.wav"
    # - "./configs/inference/audio_files/shubh.wav"
    # - "/viscam/u/shubh/Moore-AnimateAnyone/video_dir/test.wav"
    


    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
  #   - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  # "./configs/inference/ref_images/anyone-10.png":
  #   - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
  #   - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  # "./configs/inference/ref_images/anyone-11.png":
  #   - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
  #   - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  # "./configs/inference/ref_images/anyone-3.png":
  #   - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  #   - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  # "./configs/inference/ref_images/anyone-5.png":
  #   - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
